### PR TITLE
Fix deprecated Int32Value for node12

### PR DESCRIPTION
**Pull request by KimNyholm**
See issue [Int32Value() deprecated with node 12](https://github.com/jhead/node-svmq/issues/4)

### CODE REVIEW

**Comment by jhead** [comment]
Thanks for the PR! @KimNyholm

Small nitpick, could we use the shorter syntax described here?
https://github.com/bcoin-org/bcrypto/issues/7#issuecomment-498964097

```c++
Nan::To<int32_t>(info[0]).FromJust()
```

**Comment by KimNyholm** [comment]
Something like this?

**Comment by jhead** [comment]
Looks good to me, thanks! If there's no rush to release it, I'd like to fix the other deprecated calls and add a test first.

**Comment by jhead** [comment]
v1.0.7 published, I'll get to the other stuff later.

**Pull request merged**
